### ISSUE TITLE
Cannot access needed .jar file if a parent folder has an unsupported unicode symbol in the name.

### ISSUE THREAD

**Issue by paandock** [Araxeus/PNG-Upscale#114]
It very simply isn't supported, and the error doesn't tell you the culprit, So the user wastes time figuring out why the executable cannot launch.

the unicode character that I wanted to use: ｜
platform: Windows 11

suggestions:

1: add a readme that explains not to use such characters.
2: create an error dialog that properly explains what is wrong, so the user isn't lost in the woods trying to figure out the problem.
3: add support for more unicode characters than what is currently allowed.

**Comment by Araxeus** [comment]
Sounds like an issue with java and not the program itself 🤷‍♂️
