### ISSUE TITLE
downloading models

### ISSUE THREAD

**Issue by idkman2021** [Araxeus/PNG-Upscale#81]
mediafire requires premium subscription to download all files at once, could you please reupload them somewhere else

**Comment by Araxeus** [comment]
I'm sorry about that, Mediafire used to be better

I've uploaded the files to Google Drive (tell me if you have a better idea)
https://drive.google.com/drive/folders/1pMvzL5sqTRcJOhByU_Am5vU2oik_KHH2?usp=sharing

You can also download the models folder directly from GitHub:
https://download-directory.github.io/?url=https://github.com/Araxeus/PNG-Upscale/tree/main/Models

**Comment by Araxeus** [comment]
I've updated the Release and Readme to reflect the comment above
