### ISSUE TITLE
Java Runtime Error

### ISSUE THREAD

**Issue by Ohrwerk** [Araxeus/PNG-Upscale#88]
I always get the following error message on Windows x64.
Which Java Runtime is needed please?

Java Version: jre-8u341-windows-x64.exe
JAVA Virtual Machine Launcher
Error: A JNI error has occurred, please check your installation and try again.
A Java Exception has accurred.

**Comment by Araxeus** [comment]
you need JDK 15 - see https://github.com/Araxeus/PNG-Upscale/issues/33 (its also on the readme)

**Comment by Ohrwerk** [comment]
Many thanks
