### ISSUE TITLE
Question: how do I use this exactly, and can it be used on Android?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Araxeus/PNG-Upscale#97]
As Android is based on Linux, I wonder how can I use it within an Android app.

My questions:
1. Is it possible?
2. What are the requirements?
3. Suppose I want to upscale some small images to 512x512 pixels, would such a thing take a lot of resources/time?
4. Are there any examples of how to use it on Java?

**Comment by Araxeus** [comment]
1. Yes since this is written in java
2. OpenCV
   https://docs.opencv.org/4.x/d5/d29/tutorial_dnn_superres_upscale_image_single.html
   http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_dnn_superres/DnnSuperResImpl.html
3. Depands how good is your cpu
4. Yes, this repo is a pretty good example 😅
    https://github.com/Araxeus/PNG-Upscale/blob/main/src/main/java/core/Upscale.java

**Comment by AndroidDeveloperLB** [comment]
1. Interesting.
2. What do you mean? The user will have to install something? Or I need to import some library? 
3. What about RAM ? Mobile devices often have not much of it... Does it know how to deal with this automatically?
4. By looking at the code, seems ImageIcon  is used there (can't be used on Android), but only to test the size of the image, so it should be fine (Android has its own classes for this). Other than that, it seems there is actually a requirement, of not resizing to more than 6666 in height/width.  Seems reasonable too (weird number, but still fine). 
I hope I will succeed.
5. Is there a gradle dependency? What are my options of how to import the library? I just need to download the jar file and that's it? Nothing more than this?

**Comment by Araxeus** [comment]
Sorry but i'm not about to teach you how to develop android apps or use openCV. this is a desktop app

Here's a guide to get you started:
https://opencv.org/android/

**Comment by AndroidDeveloperLB** [comment]
@Araxeus Thank you for your time.

**Comment by Araxeus** [comment]
you literally asked how to use this on android. the answer is in the link I posted 🙂

**Comment by Araxeus** [comment]
Check out this project:

https://github.com/Lucchetto/SuperImage
